[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --always-print-stacktrace --chip STM32G0B1CBTx"

rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"
