[package]
name = "zencan-macro"
version = "0.0.1"
authors = ["Jeff McBride <jeff@jeffmcbride.net>"]
description = "Macro crate for zencan"

edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
zencan-build.workspace = true
zencan-common = { workspace = true, features = ["log", "std"] }
syn = "2.0.102"
proc-macro2 = "1.0.95"
quote = "1.0.40"
darling = "0.20.11"
