[package]
name = "zencan-eds"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
configparser = "3.1"
snafu.workspace = true

zencan-common = { path = "../zencan-common" }

[dev-dependencies]
tempfile = "*"
